_core:
  default_config_hash: '-oeXHVXl-m1HE6XR_-FXfNgJOgPuHcOCWSkymfOR7Sc'
langcode: fr
buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>\r\n<a class=\"a2a_button_whatsapp\"></a>\r\n<a class=\"a2a_button_email\"></a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 1
  node: 1
  comment: 0
  block_content: 0
  contact_message: 0
  file: 0
  menu_link_content: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
no_3p: false
