site_owner: '(J.I.R Ltd) '
site_address_line_1: 'KG 28 Ave #72 - Kimihurura'
site_address_line_2: 'P.O. Box 4062 Kigali, RWANDA'
site_phone: '(+250) 788 300 952'
site_target_country: RW
stats_url: ''
