our_services: 'Advertisement | Shortlisting | Recruitment | Marketing | Labour Market Data'
our_sites: 'jobinuganda.com: www.jobinuganda.com|jobintanzania.com: www.jobintanzania.com|jobinkenya.com: www.jobinkenya.com|jobinburundi.com: www.jobinburundi.com|jobincameroun.com: www.jobincameroun.com|jobenrdc.com: www.jobenrdc.com'
