entity_type_groups:
  path_alias:
    path_alias:
      basic: basic
      advanced: advanced
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_abstract: null
  metatag_maxlength_description: null
